name: Publish

on:
  release:
    types: [published]

jobs:
  test:
    uses: ./github/workflows/test.yml

  publish:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1